//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoDownloader.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DownloadApplication {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DownloadApplication() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VideoDownloader.Resources.DownloadApplication", typeof(DownloadApplication).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baixando vídeo....
        /// </summary>
        public static string Baixando_Video {
            get {
                return ResourceManager.GetString("Baixando_Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comando desconhecido: &apos;{0}&apos;.
        /// </summary>
        public static string Console_ComandoInvalido {
            get {
                return ResourceManager.GetString("Console_ComandoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro: {0}.
        /// </summary>
        public static string Console_Erro {
            get {
                return ResourceManager.GetString("Console_Erro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL inválida: &apos;{0}&apos;.
        /// </summary>
        public static string Console_UrlInvalida {
            get {
                return ResourceManager.GetString("Console_UrlInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uso: vdm &lt;comando&gt; [argumentos]
        ///
        ///Comandos:
        ///  video &lt;url&gt; [qualidade]   Baixa um vídeo (padrão: 1080p)
        ///  audio &lt;url&gt;               Baixa o áudio
        ///  playlist &lt;url&gt;            Baixa todos os vídeos da playlist
        ///  mostrar &lt;url&gt;             Lista os vídeos de uma playlist
        ///  help                       Mostra esta ajuda.
        /// </summary>
        public static string Console_Uso {
            get {
                return ResourceManager.GetString("Console_Uso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uso: vdm audio &lt;url&gt;.
        /// </summary>
        public static string Console_UsoAudio {
            get {
                return ResourceManager.GetString("Console_UsoAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uso: vdm mostrar &lt;url&gt;.
        /// </summary>
        public static string Console_UsoMostrar {
            get {
                return ResourceManager.GetString("Console_UsoMostrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uso: vdm playlist &lt;url&gt;.
        /// </summary>
        public static string Console_UsoPlaylist {
            get {
                return ResourceManager.GetString("Console_UsoPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uso: vdm video &lt;url&gt; [qualidade].
        /// </summary>
        public static string Console_UsoVideo {
            get {
                return ResourceManager.GetString("Console_UsoVideo", resourceCulture);
            }
        }
    }
}
